### ISSUE TITLE
Apply changes from master branch of hyperion plugin

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/telos-evm-rpc#3]
Currently this repo is based off the `evm_upgrade_rebase` branch of the hyperion plugin, need to check the diff between `master` and `evm_upgrade_rebase` and apply those changes to this repo.

**Comment by guilledk** [comment]
Ive checkout what commits where diferent and i think its not even worth it to port them over, one was a dependency downgrade we no longer need and other hyperion related deps stuff, so im closing this.
