### ISSUE TITLE
Feature: Add eth_getTransactionByBlockHashAndIndex endpoint support

### ISSUE THREAD

**Issue by craigbranscom** [telosnetwork/telos-evm-rpc#72]
## Overview

The RPC currently does not support the standard eth_getTransactionByBlockHashAndIndex endpoint. Add support for this endpoint to the RPC.

## Links

[Example](https://etclabscore.github.io/core-geth/JSON-RPC-API/modules/eth/#eth_gettransactionbyblockhashandindex)

## Acceptance Criteria

Endpoint is stable and returns expected output in the correct format.

## Tasks

Update the RPC src and add the eth_getTransactionByBlockHashAndIndex endpoint.

**Comment by jbuice** [comment]
@craigbranscom v1.5 was supposed to support this and does seem to kind of want to work in the latest RPC release but Tom has reported an ES issue of some sort. I am going to assign this to Tom for visibility,  @rozzaswap
