### ISSUE TITLE
RPC should return user input gas price.

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-evm-rpc#98]
# In which responses does this need to be included, how does it need to be included, how does it affect the expectations of current rpc users?

# Describe the bug

The JSON-RPC API for the Telos EVM blockchain does not return the gas price used to generate the transaction signature, making it impossible for clients to verify the validity of the signature and detect potential fake transactions returned by a malicious RPC.

## Expected behavior

The JSON-RPC API should return two separate gas price values:

1. The gas price provided by the user and used for generating the transaction signature.
2. The effective gas price that is actually used by the network (which might be a constant value).

This would allow clients to verify the validity of the transaction signature and detect any potential tampering or fake transactions returned by the RPC.

**Comment by tomtomcrypto** [comment]
We seem to be missing effectiveGasPrice in receipt, that may be the issue. I don't see anything else
